<?php

$decorator = array('ViewHelper',
 							array( 'Label' , array( 'class' => 'label' )),
							//'Errors',
							'Description',
							array( 'HtmlTag', array( 'tag' => 'p' ))
						  );
						  
$buttonDecorator = array( 'ViewHelper',
								  array( 'HtmlTag', array( 'tag' => 'p' ))
						  );

$this->form->clearDecorators();		

$this->form->login		->setDecorators($decorator)
				  		->setLabel('Identifiant :');
$this->form->password	->setDecorators($decorator)
					 	->setLabel('Mot de passe :');
$this->form->password2	->setDecorators($decorator)
					  	->setLabel('Confirmation du mot de passe :');
$this->form->civilite	->setDecorators($decorator)
				     	->setLabel('Civilité :');
$this->form->nom		->setDecorators($decorator)
						->setLabel('Nom :');
$this->form->prenom		->setDecorators($decorator)
				   		->setLabel('Prénom :');				   
$this->form->email		->setDecorators($decorator)
				  		->setLabel('Email :');
$this->form->telephone	->setDecorators($decorator)
					  	->setLabel('Téléphone :');
$this->form->send		->setDecorators($buttonDecorator)
				   		->setLabel( 'Enregistrer' )
			       		->setAttrib('class' , 'button' );

$this->form->addDisplayGroup( array( 'login', 
									 'password',
									 'password2'
									),
							   'loginGroup',
							   array( 'disableLoadDefaultDecorators' => true )
							   );
							   
$this->form->addDisplayGroup( array( 'civilite', 
									 'nom',
									 'prenom',
									 'email',
									 'telephone',
									),
							   'identityGroup',
							   array( 'disableLoadDefaultDecorators' => true )
							   );
$this->form->setDisplayGroupDecorators(array( 'FormElements',
											  'Fieldset',
											  array( array( 'outer' => 'HtmlTag' ), 
											  		 array( 'tag' => 'div', 
											  				'class' => 'fields')
														  ),
											       )
									   );
									   
$this->form->loginGroup		->setOrder( 1 )
					   		->setLegend( 'Identifiants' );
					   		
$this->form->identityGroup	->setOrder( 2 )
		   				  	->setLegend( 'Identité' );
		   				  	
$this->form->send->setOrder( 3 );

$this->form->setDecorators( array(  'FormErrors',
							 		'FormElements',
							 		'Form' ) 
						  );
echo PHP_EOL;			  
echo $this->form; 